language: php

php:
  - 7.1

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev

script: vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text